# GENERATED by extract_thirdparty.py from modules/cvtt/SCsub -- do not edit by hand.
set(GODOT_TP_CVTT_SOURCES
  thirdparty/cvtt/ConvectionKernels_API.cpp
  thirdparty/cvtt/ConvectionKernels_ETC.cpp
  thirdparty/cvtt/ConvectionKernels_BC67.cpp
  thirdparty/cvtt/ConvectionKernels_IndexSelector.cpp
  thirdparty/cvtt/ConvectionKernels_BC6H_IO.cpp
  thirdparty/cvtt/ConvectionKernels_S3TC.cpp
  thirdparty/cvtt/ConvectionKernels_BC7_PrioData.cpp
  thirdparty/cvtt/ConvectionKernels_SingleFile.cpp
  thirdparty/cvtt/ConvectionKernels_BCCommon.cpp
  thirdparty/cvtt/ConvectionKernels_Util.cpp
)
