# GENERATED by extract_thirdparty.py from modules/enet/SCsub -- do not edit by hand.
set(GODOT_TP_ENET_SOURCES
  thirdparty/enet/enet_godot.cpp
  thirdparty/enet/callbacks.c
  thirdparty/enet/compress.c
  thirdparty/enet/host.c
  thirdparty/enet/list.c
  thirdparty/enet/packet.c
  thirdparty/enet/peer.c
  thirdparty/enet/protocol.c
)
