# GENERATED by extract_thirdparty.py from modules/etcpak/SCsub -- do not edit by hand.
set(GODOT_TP_ETCPAK_SOURCES
  thirdparty/etcpak/DecodeRGB.cpp
  thirdparty/etcpak/Dither.cpp
  thirdparty/etcpak/ProcessDxtc.cpp
  thirdparty/etcpak/ProcessRGB.cpp
  thirdparty/etcpak/Tables.cpp
)
