# GENERATED by extract_thirdparty.py from modules/navigation_2d/SCsub -- do not edit by hand.
set(GODOT_TP_NAVIGATION_2D_SOURCES
  thirdparty/rvo2/rvo2_2d/Agent2d.cpp
  thirdparty/rvo2/rvo2_2d/Obstacle2d.cpp
  thirdparty/rvo2/rvo2_2d/KdTree2d.cpp
  thirdparty/rvo2/rvo2_2d/RVOSimulator2d.cpp
)
