# GENERATED by extract_thirdparty.py from modules/upnp/SCsub -- do not edit by hand.
set(GODOT_TP_UPNP_SOURCES
  thirdparty/miniupnpc/src/igd_desc_parse.c
  thirdparty/miniupnpc/src/miniupnpc.c
  thirdparty/miniupnpc/src/minixml.c
  thirdparty/miniupnpc/src/minisoap.c
  thirdparty/miniupnpc/src/minissdpc.c
  thirdparty/miniupnpc/src/miniwget.c
  thirdparty/miniupnpc/src/upnpcommands.c
  thirdparty/miniupnpc/src/upnpdev.c
  thirdparty/miniupnpc/src/upnpreplyparse.c
  thirdparty/miniupnpc/src/connecthostport.c
  thirdparty/miniupnpc/src/portlistingparse.c
  thirdparty/miniupnpc/src/receivedata.c
  thirdparty/miniupnpc/src/addr_is_reserved.c
)
