# GENERATED by extract_thirdparty.py from modules/vhacd/SCsub -- do not edit by hand.
set(GODOT_TP_VHACD_SOURCES
  thirdparty/vhacd/src/vhacdManifoldMesh.cpp
  thirdparty/vhacd/src/FloatMath.cpp
  thirdparty/vhacd/src/vhacdMesh.cpp
  thirdparty/vhacd/src/vhacdICHull.cpp
  thirdparty/vhacd/src/vhacdVolume.cpp
  thirdparty/vhacd/src/VHACD-ASYNC.cpp
  thirdparty/vhacd/src/btAlignedAllocator.cpp
  thirdparty/vhacd/src/vhacdRaycastMesh.cpp
  thirdparty/vhacd/src/VHACD.cpp
  thirdparty/vhacd/src/btConvexHullComputer.cpp
)
