# GENERATED by extract_thirdparty.py from modules/websocket/SCsub -- do not edit by hand.
set(GODOT_TP_WEBSOCKET_SOURCES
  thirdparty/wslay/wslay_net.c
  thirdparty/wslay/wslay_event.c
  thirdparty/wslay/wslay_queue.c
  thirdparty/wslay/wslay_frame.c
)
